pipeline {
  agent any

  environment {
    IMAGE_NAME = "amansain01/portfolio-ui"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('SonarQube Scan') {
      steps {
    withSonarQubeEnv('SonarQube') {
      withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
        sh '''
          cd frontend
          sonar-scanner \
            -Dsonar.projectKey=portfolio-ui \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=$SONAR_TOKEN
        '''
      }
    }
  }
    }

    stage('Trivy Scan') {
      steps {
        sh 'trivy fs .'
        sh 'trivy image --severity HIGH,CRITICAL --exit-code 1 $IMAGE_NAME || true'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t $IMAGE_NAME:latest .'
      }
    }

    stage('Push Image') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'docker-creds',
          usernameVariable: 'USER',
          passwordVariable: 'PASS'
        )]) {
          sh '''
            echo $PASS | docker login -u $USER --password-stdin
            docker push $IMAGE_NAME:latest
          '''
        }
      }
    }
  }
}
