pipeline {
  agent any

  environment {
    IMAGE_NAME = "amansain01/portfolio-ui"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('SonarQube Scan') {
      steps {
        withSonarQubeEnv('SonarQube') {
          withCredentials([string(credentialsId: 'sonar-token2', variable: 'SONAR_TOKEN')]) {
            sh '''
              cd frontend
              sonar-scanner \
                -Dsonar.projectKey=portfolio-ui \
                -Dsonar.sources=. \
                -Dsonar.login=$SONAR_TOKEN
            '''
          }
        }
      }
    }

    stage('Trivy FS Scan') {
      steps {
        sh '''
          cd frontend
          trivy fs .
        '''
      }
    }

    stage('Build Docker Image') {
      steps {
        sh '''
          cd frontend
          docker build -t $IMAGE_NAME:latest .
        '''
      }
    }

    stage('Trivy Image Scan') {
      steps {
        sh '''
          trivy image --severity HIGH,CRITICAL --exit-code 1 $IMAGE_NAME:latest || true
        '''
      }
    }

    stage('Push Image') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'docker-creds',
          usernameVariable: 'USER',
          passwordVariable: 'PASS'
        )]) {
          sh '''
            echo $PASS | docker login -u $USER --password-stdin
            docker push $IMAGE_NAME:latest
          '''
        }
      }
    }
  }
}
