pipeline {
  agent any

  environment {
    IMAGE_NAME = "amansain01/portfolio-ui"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('SonarQube Scan') {
      steps {
        withSonarQubeEnv('SonarQube') {
          sh 'sonar-scanner'
        }
      }
    }

    stage('Trivy Scan') {
      steps {
        sh 'trivy fs .'
        sh 'trivy image --severity HIGH,CRITICAL --exit-code 1 $IMAGE_NAME || true'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t $IMAGE_NAME:latest .'
      }
    }

    stage('Push Image') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'docker-creds',
          usernameVariable: 'USER',
          passwordVariable: 'PASS'
        )]) {
          sh '''
            echo $PASS | docker login -u $USER --password-stdin
            docker push $IMAGE_NAME:latest
          '''
        }
      }
    }
  }
}
